### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by imaia** [centosadmin/redmine_2fa#21]
I'm testing out 2fa in my development environment and get an 502 Bad Gateway error when the plugin is enabled. Are there known causes for it?

**Comment by imaia** [comment]
Actually, after restarting, it kind of worked. Now, when I login, there is a server error message. I'm using docker. Is there any suggestions on how to proceed?

**Comment by olemskoi** [comment]
Can you please attach production.log?

**Comment by imaia** [comment]
```
Started GET "/" for 172.19.0.4 at 2016-12-19 13:08:02 -0300
Processing by WelcomeController#index as HTML
  Current user: anonymous
  Rendered welcome/index.html.erb within layouts/base (21.8ms)
Completed 200 OK in 246ms (Views: 150.0ms | ActiveRecord: 12.4ms)
Started GET "/login" for 172.19.0.4 at 2016-12-19 13:08:04 -0300
Processing by AccountController#login as HTML
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (4.0ms)
Completed 200 OK in 13ms (Views: 10.0ms | ActiveRecord: 1.2ms)
Started POST "/login" for 172.19.0.4 at 2016-12-19 13:08:06 -0300
Processing by AccountController#login as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"TOKEN", "back_url"=>"http://127.0.0.1/", "username"=>"admin", "password"=>"[FILTERED]", "login"=>"Entrar »"}
  Current user: anonymous
Completed 500 Internal Server Error in 66ms (ActiveRecord: 59.6ms)

NoMethodError (undefined method `ignore_2fa?' for #<User:0x007fd54e095af8>):
  plugins/redmine_2fa-master/lib/redmine_2fa/patches/account_controller_patch/second_authentication_init.rb:8:in `password_authentication'
  plugins/redmine_2fa-master/lib/redmine_2fa/patches/account_controller_patch/second_authentication_prepare.rb:12:in `password_authentication'
  app/controllers/account_controller.rb:191:in `authenticate_user'
  app/controllers/account_controller.rb:40:in `login'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

**Comment by olemskoi** [comment]
Did you run migrations and bundle install?

**Comment by imaia** [comment]
I think so, but I'm not quite sure. How do I check if I did?

**Comment by olemskoi** [comment]
Execute it one more time and put log here.

**Comment by imaia** [comment]
@olemskoi here is what happened: I was downloading the latest 2fa from github using wget. I think a naming problem happened after I placed the plugin in the plugins folder, as the plugin name had "-master" appended to it. Now it works. Thanks!
