### ISSUE TITLE
Internal error - if redmine works with passenger

### ISSUE THREAD

**Issue by fgrosswig** [centosadmin/redmine_2fa#24]
We have redmine through passenger up and running, so we guess the error which is statet as follow, results in not having redmine listening to that redmine specfic port.

may this be dynamically changed? and if yes, where? 

`URI::InvalidComponentError (bad component(expected host component): [localhost:3000]):
  plugins/redmine_2fa/app/controllers/otp_bot_controller.rb:42:in 'set_bot_webhook'
  plugins/redmine_2fa/app/controllers/otp_bot_controller.rb:8:in 'create'
  lib/redmine/sudo_mode.rb:63:in 'sudo_mode'`

regards,
Falk

**Comment by fgrosswig** [comment]
REdmine setting in backend - closing this issue due misleading configuration on our own.
