### ISSUE TITLE
install failed with syntax error

### ISSUE THREAD

**Issue by luozengbin** [centosadmin/redmine_2fa#30]
```
root@redmine:/usr/src/redmine# bin/rake redmine:plugins:migrate        
/usr/local/bundle/gems/htmlentities-4.3.1/lib/htmlentities/mappings/expanded.rb:465: warning: duplicated key at line 466 ignored: "inodot"
yardoc failed.
/usr/src/redmine/plugins/redmine_2fa/lib/redmine_2fa/code_sender.rb:26: warning: else without rescue is useless
rake aborted!
SyntaxError: /usr/src/redmine/plugins/redmine_2fa/lib/redmine_2fa/code_sender.rb:19: syntax error, unexpected '.'
      case user&.auth_source&.auth_method_name
                 ^
/usr/src/redmine/plugins/redmine_2fa/lib/redmine_2fa/code_sender.rb:22: syntax error, unexpected keyword_when, expecting keyword_end
      when 'SMS'
          ^
/usr/src/redmine/plugins/redmine_2fa/lib/redmine_2fa/code_sender.rb:38: syntax error, unexpected keyword_end, expecting end-of-input
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:360:in `require_or_load'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:317:in `depend_on'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:233:in `require_dependency'
/usr/src/redmine/plugins/redmine_2fa/init.rb:12:in `block (3 levels) in <top (required)>'
/usr/src/redmine/plugins/redmine_2fa/init.rb:11:in `each'
/usr/src/redmine/plugins/redmine_2fa/init.rb:11:in `block (2 levels) in <top (required)>'
/usr/src/redmine/plugins/redmine_2fa/init.rb:10:in `each'
/usr/src/redmine/plugins/redmine_2fa/init.rb:10:in `block in <top (required)>'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:446:in `instance_exec'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:192:in `call'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:192:in `block in simple'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `block in call'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `each'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/usr/local/bundle/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/usr/src/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
/usr/local/bundle/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
root@redmine:/usr/src/redmine# 

```

**Comment by olemskoi** [comment]
Which ruby version do you use?

**Comment by luozengbin** [comment]
```
root@redmine:/usr/src/redmine# ruby -v
ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-linux]
```

**Comment by olemskoi** [comment]
Please try using ruby >= 2.3.
