### ISSUE TITLE
Install error with docker-redmine

### ISSUE THREAD

**Issue by kk17** [centosadmin/redmine_2fa#40]
I am running redmine using [sameersbn/docker-redmine](https://github.com/sameersbn/docker-redmine#installing-plugins) and I am trying to install this plugin follow the instructions from [here](https://github.com/sameersbn/docker-redmine#installing-plugins). I cloned this repository into directory `/srv/docker/redmine/redmine/plugins`, but when I restart redmine I got this error:

```
redmine_1  | Installing plugins...
redmine_1  | Installing gems required by plugins...
redmine_1  | Migrating plugins. Please be patient, this could take a while...
redmine_1  | /home/redmine/redmine/plugins/redmine_2fa/lib/redmine_2fa/code_sender.rb:26: warning: else without rescue is useless
redmine_1  | rake aborted!
redmine_1  | SyntaxError: /home/redmine/redmine/plugins/redmine_2fa/lib/redmine_2fa/code_sender.rb:19: syntax error, unexpected '.'
redmine_1  |       case user&.auth_source&.auth_method_name
redmine_1  |                  ^
redmine_1  | /home/redmine/redmine/plugins/redmine_2fa/lib/redmine_2fa/code_sender.rb:22: syntax error, unexpected keyword_when, expecting keyword_end
redmine_1  |       when 'SMS'
redmine_1  |           ^
redmine_1  | /home/redmine/redmine/plugins/redmine_2fa/lib/redmine_2fa/code_sender.rb:38: syntax error, unexpected keyword_end, expecting end-of-input
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:360:in `require_or_load'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:317:in `depend_on'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:233:in `require_dependency'
redmine_1  | /home/redmine/redmine/plugins/redmine_2fa/init.rb:12:in `block (3 levels) in <top (required)>'
redmine_1  | /home/redmine/redmine/plugins/redmine_2fa/init.rb:11:in `each'
redmine_1  | /home/redmine/redmine/plugins/redmine_2fa/init.rb:11:in `block (2 levels) in <top (required)>'
redmine_1  | /home/redmine/redmine/plugins/redmine_2fa/init.rb:10:in `each'
redmine_1  | /home/redmine/redmine/plugins/redmine_2fa/init.rb:10:in `block in <top (required)>'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:446:in `instance_exec'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:446:in `block in make_lambda'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:192:in `call'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:192:in `block in simple'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `block in call'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `each'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:504:in `call'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
redmine_1  | /home/redmine/redmine/config/environment.rb:14:in `<top (required)>'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
redmine_1  | Tasks: TOP => redmine:plugins:migrate => environment
redmine_1  | (See full trace by running task with --trace)
```

The docker image I am using is sameersbn/redmine:3.3.2-1. I am not familiar with ruby so I really hope you can help me.

**Comment by olemskoi** [comment]
Which version of ruby do you use? Can you please try 2.4.1?

**Comment by kk17** [comment]
2.1.0
I am now using redmine 3.4.2 with ruby 2.3.x and the issue gone.
