### ISSUE TITLE
No route for confirming otp_code

### ISSUE THREAD

**Issue by akhilesharora** [centosadmin/redmine_2fa#50]
#Routing Error
No route matches [GET] "/redmine_2fa/otp_code/confirm"

```Started POST "/redmine_2fa/otp_code/confirm" for 127.0.0.1 at 2018-03-13 21:32:00 +0100
Processing by AccountController#confirm_otp as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"tuGTzcMdlVSubTIBFZszFLLttRl4a44rARwJYL7XB3XMy+ZLz0Vlqr7mDCMpDZx2v0sl8ywy4OYKHhL5BJgKLg==", "otp_code"=>"904307", "login"=>"Login »"}
   (0.3ms)  SELECT MAX(`settings`.`updated_on`) FROM `settings`
  AnonymousUser Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('AnonymousUser')  ORDER BY `users`.`id` ASC LIMIT 1
  Current user: anonymous
  User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`id` = 7 LIMIT 1
Successful authentication for 'test3' from 127.0.0.1 at 2018-03-13 20:32:00 UTC
   (0.2ms)  BEGIN
  Token Exists (0.3ms)  SELECT  1 AS one FROM `tokens` WHERE `tokens`.`value` = BINARY '' LIMIT 1
  CACHE (0.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`id` = 7 LIMIT 1  [["id", 7]]
   (0.4ms)  SELECT `tokens`.`id` FROM `tokens` WHERE `tokens`.`user_id` = 7 AND `tokens`.`action` = 'session'  ORDER BY `tokens`.`updated_on` DESC LIMIT 18446744073709551615 OFFSET 9
  SQL (0.3ms)  INSERT INTO `tokens` (`user_id`, `action`, `created_on`, `updated_on`, `value`) VALUES (7, 'session', '2018-03-13 21:32:00', '2018-03-13 21:32:00', 'b207f0f034a97d57b81addd6c4d7cb03f9ac6c5c')
   (2.2ms)  COMMIT
  Setting Load (0.4ms)  SELECT  `settings`.* FROM `settings` WHERE `settings`.`name` = 'password_max_age'  ORDER BY `settings`.`id` DESC LIMIT 1
Redirected to http://localhost:3000/redmine_2fa/otp_code/confirm
Completed 302 Found in 21ms (ActiveRecord: 4.8ms)


Started GET "/redmine_2fa/otp_code/confirm" for 127.0.0.1 at 2018-03-13 21:32:00 +0100

ActionController::RoutingError (No route matches [GET] "/redmine_2fa/otp_code/confirm"):
  actionpack (4.2.8) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.8) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.8) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.8) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.9) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.9) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.8) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.9) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.9) lib/rack/content_length.rb:15:in `call'
  rack (1.6.9) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.8) lib/rails/engine.rb:518:in `call'
  railties (4.2.8) lib/rails/application.rb:165:in `call'
  rack (1.6.9) lib/rack/lock.rb:17:in `call'
  rack (1.6.9) lib/rack/content_length.rb:15:in `call'
  rack (1.6.9) lib/rack/handler/webrick.rb:88:in `service'
  /usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'


  Rendered /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (0.9ms)
  Rendered /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/routes/_route.html.erb (10.7ms)
  Rendered /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/routes/_table.html.erb (2.0ms)
  Rendered /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /var/lib/gems/2.3.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (72.5ms)
```

**Comment by olemskoi** [comment]
What is your hostname in Redmine settings? Do you use https?

**Comment by akhilesharora** [comment]
No. I am just using localhost:3000 currently.

**Comment by olemskoi** [comment]
This plugin requires working domain with valid https. It is needed by Telegram webhook.
