### ISSUE TITLE
No such file to load in Production

### ISSUE THREAD

**Issue by akhilesharora** [centosadmin/redmine_2fa#51]
```
sudo rails s -b 0.0.0.0 -e production
=> Booting WEBrick
=> Rails 4.2.8 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require': No such file to load -- telegram_handler_worker (LoadError)
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:360:in `require_or_load'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:317:in `depend_on'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:233:in `require_dependency'
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:471:in `each'
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:471:in `block in eager_load!'
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:469:in `each'
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:469:in `eager_load!'
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:346:in `eager_load!'
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/application/finisher.rb:56:in `each'
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
	from /home/akhilesh/Documents/code/redmine_test/config/environment.rb:14:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /home/akhilesh/Documents/code/redmine_test/config.ru:3:in `block in <main>'
	from /var/lib/gems/2.3.0/gems/rack-1.6.9/lib/rack/builder.rb:55:in `instance_eval'
	from /var/lib/gems/2.3.0/gems/rack-1.6.9/lib/rack/builder.rb:55:in `initialize'
	from /home/akhilesh/Documents/code/redmine_test/config.ru:in `new'
	from /home/akhilesh/Documents/code/redmine_test/config.ru:in `<main>'
	from /var/lib/gems/2.3.0/gems/rack-1.6.9/lib/rack/builder.rb:49:in `eval'
	from /var/lib/gems/2.3.0/gems/rack-1.6.9/lib/rack/builder.rb:49:in `new_from_string'
	from /var/lib/gems/2.3.0/gems/rack-1.6.9/lib/rack/builder.rb:40:in `parse_file'
	from /var/lib/gems/2.3.0/gems/rack-1.6.9/lib/rack/server.rb:300:in `build_app_and_options_from_config'
	from /var/lib/gems/2.3.0/gems/rack-1.6.9/lib/rack/server.rb:209:in `app'
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands/server.rb:61:in `app'
	from /var/lib/gems/2.3.0/gems/rack-1.6.9/lib/rack/server.rb:337:in `wrapped_app'
	from /var/lib/gems/2.3.0/gems/rack-1.6.9/lib/rack/server.rb:273:in `start'
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands/server.rb:80:in `start'
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

```

**Comment by olemskoi** [comment]
Please read README file in repository. Check if you installed redmine telegram common plugin.

**Comment by akhilesharora** [comment]
Its already installed.
